# Generated by Django 6.0.1 on 2026-01-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productspecification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecification',
            old_name='name',
            new_name='key',
        ),
    ]
