# Generated by Django 6.0.3 on 2026-03-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_add_discount_and_fix_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã giảm giá (vd: SALE10)', max_length=50, unique=True)),
                ('discount_percent', models.IntegerField(help_text='% giảm giá (vd: 10 = 10%)')),
                ('description', models.CharField(blank=True, help_text='Mô tả mã coupon', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Kích hoạt/Vô hiệu hóa mã')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
