# Generated by Django 6.0.3 on 2026-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
