# Generated by Django 6.0.3 on 2026-03-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_discountcode_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB')], help_text='Chọn RAM hoặc ROM', max_length=20)),
                ('price_increase', models.IntegerField(default=0, help_text='Giá tăng thêm (VND)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['variant_type'],
                'unique_together': {('product', 'variant_type')},
            },
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
