# Generated by Django 6.0.3 on 2026-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productvariant_delete_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB')], default='8GB', help_text='Bộ nhớ RAM', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rom',
            field=models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], default='128GB', help_text='Bộ nhớ ROM', max_length=10),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
