# Generated by Django 6.0.3 on 2026-03-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_ram_product_rom_delete_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'Đen'), ('white', 'Trắng'), ('blue', 'Xanh lam'), ('dark_blue', 'Xanh đậm'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('rose_gold', 'Rose Gold'), ('orange', 'Cam'), ('cosmic_orange', 'Cam Vũ Trụ'), ('purple', 'Tím'), ('pink', 'Hồng'), ('red', 'Đỏ'), ('green', 'Xanh lục')], max_length=20)),
                ('rom', models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], max_length=10)),
                ('price', models.IntegerField(help_text='Giá của phiên bản này')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_colors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.product')),
            ],
            options={
                'ordering': ['rom', 'color'],
                'unique_together': {('product', 'color', 'rom')},
            },
        ),
    ]
