# Generated by Django 6.0.3 on 2026-03-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'Đen'), ('white', 'Trắng'), ('blue', 'Xanh lam'), ('dark_blue', 'Xanh đậm'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('rose_gold', 'Rose Gold'), ('orange', 'Cam'), ('cosmic_orange', 'Cam Vũ Trụ'), ('purple', 'Tím'), ('pink', 'Hồng'), ('red', 'Đỏ'), ('green', 'Xanh lục')], max_length=20)),
                ('price', models.IntegerField(default=0, help_text='Giá của variant này, để trống dùng giá product')),
                ('image', models.ImageField(help_text='Hình ảnh chính cho variant này', upload_to='product_variants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['color'],
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
