# Generated by Django 6.0.3 on 2026-03-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productvariant_productimage_delete_productcolor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng'), ('vnpay', 'VNPAY')], default='cash', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
