# Generated by Django 6.0.3 on 2026-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm (%)'), ('fixed', 'Số tiền (₫)')], default='percent', max_length=10)),
                ('discount_value', models.IntegerField(help_text='Giá trị giảm giá')),
                ('min_order_amount', models.IntegerField(default=0, help_text='Số tiền đơn hàng tối thiểu')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Số lần sử dụng tối đa (None = không giới hạn)', null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
