# Generated by Django 6.0.3 on 2026-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_wishlist_delete_voucher_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Xử lý'), ('shipped', 'Đang giao'), ('delivered', 'Hoàn tất'), ('cancelled', 'Đã huỷ')], default='pending', max_length=20),
        ),
    ]
