# Generated by Django 6.0.3 on 2026-04-25 15:56

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_banner_filefield_media_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(help_text='Banner image or video', upload_to=store.models.banner_upload_path),
        ),
    ]
