# Generated by Django 6.0.3 on 2026-04-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_product_pending_media'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS store_voucher;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
