# Generated by Django 6.0.3 on 2026-04-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_passwordresettoken_delete_voucher_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
