# Generated by Django 6.0.1 on 2026-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_delete_voucher_passwordresettoken_code_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS store_voucher (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            code VARCHAR(50) NOT NULL UNIQUE,
                            description VARCHAR(255) NOT NULL DEFAULT '',
                            discount_percent INTEGER NOT NULL DEFAULT 0,
                            usage_limit INTEGER NULL,
                            used_count INTEGER NOT NULL DEFAULT 0,
                            start_date DATE NULL,
                            end_date DATE NULL,
                            active INTEGER NOT NULL DEFAULT 1,
                            created_at DATETIME NOT NULL,
                            updated_at DATETIME NOT NULL
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS store_voucher;",
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='voucher',
                    old_name='is_active',
                    new_name='active',
                ),
                migrations.RemoveField(
                    model_name='voucher',
                    name='discount_type',
                ),
                migrations.RemoveField(
                    model_name='voucher',
                    name='discount_value',
                ),
                migrations.RemoveField(
                    model_name='voucher',
                    name='min_order_amount',
                ),
                migrations.RemoveField(
                    model_name='voucher',
                    name='times_used',
                ),
                migrations.AddField(
                    model_name='voucher',
                    name='discount_percent',
                    field=models.PositiveSmallIntegerField(default=0, help_text='Giảm giá theo phần trăm'),
                ),
                migrations.AddField(
                    model_name='voucher',
                    name='used_count',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='order',
                    name='payment_method',
                    field=models.CharField(choices=[('cash', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng'), ('vnpay', 'VNPAY'), ('vietqr', 'VIETQR'), ('momo', 'MoMo')], default='cash', max_length=20),
                ),
                migrations.AlterField(
                    model_name='voucher',
                    name='description',
                    field=models.CharField(blank=True, default='', max_length=255),
                ),
                migrations.AlterField(
                    model_name='voucher',
                    name='end_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='voucher',
                    name='start_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='voucher',
                    name='usage_limit',
                    field=models.PositiveIntegerField(blank=True, help_text='Số lần sử dụng tối đa (để trống nếu không giới hạn)', null=True),
                ),
            ],
        ),
    ]
