# Generated by Django 6.0.1 on 2026-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_rename_is_active_voucher_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đã đặt hàng'), ('shipped', 'Đang giao'), ('delivered', 'Đã giao hàng'), ('expired', 'Hết hạn thanh toán'), ('cancelled', 'Hủy đơn')], default='pending', max_length=20),
        ),
    ]
