"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
# Priority: .env.local (local override) > .env (production default)
ENV_LOCAL = BASE_DIR / '.env.local'
ENV_PROD = BASE_DIR / '.env'

# Check environment mode directly from file (before loading)
_env_mode = None
if ENV_LOCAL.exists():
    with open(ENV_LOCAL, encoding='utf-8') as f:
        for line in f:
            if line.startswith('ENVIRONMENT='):
                _env_mode = line.split('=', 1)[1].strip().lower()
                break

# Also check .env if mode not found in .env.local
if not _env_mode and ENV_PROD.exists():
    with open(ENV_PROD, encoding='utf-8') as f:
        for line in f:
            if line.startswith('ENVIRONMENT='):
                _env_mode = line.split('=', 1)[1].strip().lower()
                break

# If mode is local/development, only load .env.local
# Otherwise load production first, then local to override
if _env_mode in ('local', 'development'):
    # Local development: only load .env.local
    if ENV_LOCAL.exists():
        load_dotenv(ENV_LOCAL)
elif ENV_LOCAL.exists():
    load_dotenv(ENV_PROD)  # Load production defaults first (may not exist on server)
    load_dotenv(ENV_LOCAL, override=True)  # Then override with local settings
elif ENV_PROD.exists():
    load_dotenv(ENV_PROD)

# DEBUG must be determined AFTER loading env to check if in local mode
# If in development mode and DEBUG not explicitly set, default to True
DEBUG = os.getenv('DEBUG')
if DEBUG is not None:
    DEBUG = DEBUG.lower() == 'true'
elif _env_mode in ('local', 'development'):
    DEBUG = True
else:
    DEBUG = False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-dev-key-for-testing-only'
    else:
        raise ValueError(
            "SECRET_KEY environment variable is not set. "
            "Please add it to your .env file: SECRET_KEY=your-secret-key"
        )

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'store',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← BẮT BUỘC
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]



WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_URL = 'store:login'
LOGIN_REDIRECT_URL = 'store:home'
LOGOUT_REDIRECT_URL = 'store:login'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

# Google OAuth Configuration (optional in debug mode)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_OAUTH2_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['id', 'email', 'name', 'picture']
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = os.getenv(
    'GOOGLE_OAUTH2_REDIRECT_URI',
    'http://127.0.0.1:8000/oauth/complete/google-oauth2/' if DEBUG
    else 'http://160.187.229.147/oauth/complete/google-oauth2/'
)
SOCIAL_AUTH_URL_NAMESPACE = 'social'

# ==================== EMAIL CONFIGURATION ====================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = False

# Email credentials (optional in debug mode)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'admin@localhost' if DEBUG else None)
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'password' if DEBUG else None)

if not EMAIL_HOST_USER and not DEBUG:
    raise ValueError("EMAIL_HOST_USER environment variable is not set. Please add it to your .env file")
if not EMAIL_HOST_PASSWORD and not DEBUG:
    raise ValueError("EMAIL_HOST_PASSWORD environment variable is not set. Please add it to your .env file")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'admin@localhost'
SERVER_EMAIL = EMAIL_HOST_USER or 'admin@localhost'

VIETQR_BANK_ID = os.getenv('VIETQR_BANK_ID', 'MB')
VIETQR_BANK_NAME = os.getenv('VIETQR_BANK_NAME', 'MB Bank')
VIETQR_BANK_ACCOUNT_NO = os.getenv('VIETQR_BANK_ACCOUNT_NO', '0386220065')
VIETQR_BANK_ACCOUNT_NAME = os.getenv('VIETQR_BANK_ACCOUNT_NAME', 'LUU DUC MANH')
VIETQR_TIMEOUT_SECONDS = int(os.getenv('VIETQR_TIMEOUT_SECONDS', '900'))

# VNPAY configuration
# Sandbox: https://sandbox.vnpayment.vn/apis/docs/thanh-toan-pay/pay.html
# Production: https://pay.vnpay.vn/vpcpay.html
VNPAY_TMN_CODE = os.getenv('VNPAY_TMN_CODE', 'TEST' if _env_mode in ('local', 'development') else None)
VNPAY_HASH_SECRET = os.getenv('VNPAY_HASH_SECRET', 'SECRET' if _env_mode in ('local', 'development') else None)

if not VNPAY_TMN_CODE and _env_mode not in ('local', 'development'):
    raise ValueError("VNPAY_TMN_CODE environment variable is not set. Please add it to your .env file")
if not VNPAY_HASH_SECRET and _env_mode not in ('local', 'development'):
    raise ValueError("VNPAY_HASH_SECRET environment variable is not set. Please add it to your .env file")

# VNPay URLs - chọn sandbox hoặc production dựa trên ENVIRONMENT mode
VNPAY_SANDBOX_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
VNPAY_PRODUCTION_URL = 'https://pay.vnpay.vn/vpcpay.html'
VNPAY_URL = os.getenv('VNPAY_URL', VNPAY_SANDBOX_URL if _env_mode in ('local', 'development') else VNPAY_PRODUCTION_URL)

# Return URL - chỉ override nếu chưa có trong env
if not os.getenv('VNPAY_RETURN_URL'):
    if _env_mode in ('local', 'development'):
        VNPAY_RETURN_URL = 'http://127.0.0.1:8000/vnpay/return/'
    else:
        VNPAY_RETURN_URL = 'https://idvn.io.vn/vnpay/return/'
else:
    VNPAY_RETURN_URL = os.getenv('VNPAY_RETURN_URL')

if not os.getenv('VNPAY_IPN_URL'):
    if _env_mode in ('local', 'development'):
        VNPAY_IPN_URL = 'http://127.0.0.1:8000/vnpay/ipn/'
    else:
        VNPAY_IPN_URL = 'https://idvn.io.vn/vnpay/ipn/'
else:
    VNPAY_IPN_URL = os.getenv('VNPAY_IPN_URL')

VNPAY_API_URL = os.getenv('VNPAY_API_URL', 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html' if _env_mode in ('local', 'development') else 'https://pay.vnpay.vn/vpcpay.html')

# MOMO sandbox configuration (optional in debug mode)
MOMO_PARTNER_CODE = os.getenv('MOMO_PARTNER_CODE', 'MOMO' if DEBUG else None)
MOMO_ACCESS_KEY = os.getenv('MOMO_ACCESS_KEY', 'ACCESS_KEY' if DEBUG else None)
MOMO_SECRET_KEY = os.getenv('MOMO_SECRET_KEY', 'SECRET_KEY' if DEBUG else None)

if not MOMO_PARTNER_CODE and not DEBUG:
    raise ValueError("MOMO_PARTNER_CODE environment variable is not set. Please add it to your .env file")
if not MOMO_ACCESS_KEY and not DEBUG:
    raise ValueError("MOMO_ACCESS_KEY environment variable is not set. Please add it to your .env file")
if not MOMO_SECRET_KEY and not DEBUG:
    raise ValueError("MOMO_SECRET_KEY environment variable is not set. Please add it to your .env file")

MOMO_ENDPOINT = os.getenv('MOMO_ENDPOINT', 'https://test-payment.momo.vn/v2/gateway/api/create')
MOMO_RETURN_URL = os.getenv('MOMO_RETURN_URL', 'http://127.0.0.1:8000/momo/return/')
MOMO_IPN_URL = os.getenv('MOMO_IPN_URL', 'http://127.0.0.1:8000/momo/ipn/')
MOMO_REQUEST_TYPE = os.getenv('MOMO_REQUEST_TYPE', 'payWithATM')
MOMO_TIMEOUT_SECONDS = int(os.getenv('MOMO_TIMEOUT_SECONDS', '900'))

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '8625948551:AAGO2A4emtPJOH555z21vsO14if5F-vwuVs')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '3756857984')

